# Setup
title:               Alikhan Uzakov
tagline:             '@alikhan_uzakov'
description:         'Hi, I am Alikhan. I write about AppSec, finance, my interest in photography and technology.'
url:                 https://uzakov.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alikhan Uzakov
  url:               https://twitter.com/alikhan_uzakov
  email:             alikhanatuzakovdotio

# Gems
plugins:
  - jekyll-paginate

collections:
  varyingtopics:
    output: true
    permalink: /varyingtopics/:path/


# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
